@baseUrl = https://localhost:7130

### Створити категорію "Їжа"

POST {{baseUrl}}/api/categories

Content-Type: application/json

{
  "name": "Їжа,
  "type": "Expense",
  "icon": "🍔"
}

### Створити категорію "Зарплата"

POST {{baseUrl}}/api/categories

Content-Type: application/json

{

  "name": "Зарплата",

  "type": "Income",

  "icon": "💰"

}

### Отримати всі категорії

GET {{baseUrl}}/api/categories